name: Automated file updates

#
# TODO: FILTER TO PYTHON CHANGES
#

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./python

jobs:
  commit_changes:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: "Set up Python"
        uses: actions/setup-python@v6
        with:
          python-version-file: "./python/.python-version"

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Format Python
        run: |
          uv run genall --path buildsql
          uv run isort buildsql
          uv run black buildsql

      - name: fmting
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: add genall, isort, black fixes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Type check with mypy
        run: uv run mypy .

      - name: Run tests
        run: uv run pytest .
